config/routes.rb
Rails.application.routes.draw do
  #ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

scope module: :public do
  root to: "homes#top"
  get "about" => "homes#about", as: 'about'
  get "search" => "searches#search"
  resources :notifications, only: [:index]
  delete "destroy_all" => "notifications#destroy_all"
  resources :customers, only: [:index, :show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'

    member do
      get :favorites
    end
  end

  resources :posts, only: [:index, :show, :edit, :new, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]

    resources :comments, only: [:create, :destroy]
  end
end



  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  resources :customers, only: [:index, :show, :destroy]
  resources :posts, only: [:index, :show, :destroy]

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  has_many_attached :images
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :notifications, dependent: :destroy

  # タイトルが空欄でないことを確認している
  validates :title, presence: true
  # 投稿の説明が空欄でないことを確認している
  validates :body, presence: true

  # 検索方向分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def create_notification_by(current_customer)
	    notification = current_customer.active_notifications.new(
	      post_id: id,
	      visited_id: customer_id,
	      action: "favorite"
	    )
	    notification.save if notification.valid?
  end

  def create_notification_comment!(current_customer, comment_id)
	    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
	    temp_ids = Comment.select(:customer_id).where(post_id: id).where.not(customer_id: current_customer.id).distinct
	    temp_ids.each do |temp_id|
	        save_notification_comment!(current_customer, comment_id, temp_id['customer_id'])
      end
    	# まだ誰もコメントしていない場合は、投稿者に通知を送る
    	save_notification_comment!(current_customer, comment_id, customer_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_customer, comment_id, visited_id)
      # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
      notification = current_customer.active_notifications.new(
        post_id: id,
        comment_id: comment_id,
        visited_id: visited_id,
        action: 'comment'
        )
        # 自分の投稿に対するコメントの場合は、通知済みとする
      if notification.visiter_id == notification.visited_id
          notification.checked = true
      end
        notification.save if notification.valid?
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
    @posts = Post.page(params[:page]).per(8)
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private
  # ストロングパラメータ
  def post_params
    params.require(:post).permit(:title, :body, images: [])
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_index.html.erb
<table class="table table-hover">
  <% post.comments.each do |comment| %>
    <tr>
      <td>
        <%= link_to admin_customer_path(comment.customer) do %>
        <%= image_tag comment.customer.get_profile_image(50,50), class: "rounded-circle" %><br />
        <%= comment.customer.full_name %>
        <% end %>
      </td>
      <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
      <td><%= comment.comment %></td>
      <td><%= link_to "コメント削除", post_comment_path(comment.post,comment), method: :delete, class: 'btn btn-info rounded-pill', remote: true %></td>
      <td>
        <i class="far fa-clock clock-icon"></i><%= time_ago_in_words(comment.created_at) %>前
      </td>
    <% end %>
    </tr>
</table>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2 mt-5 border border-secondary shadow-lg p-3 rounded" style="background-color:#D0C1C2;">

      <h3>投稿一覧</h3>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>写真</th>
              <th>タイトル</th>
            </tr>
          </thead>
          <% @posts.each do |post| %>
          <tbody>
            <tr>
              <td>
                <%= link_to admin_customer_path(post.customer.id) do %>
                <%= image_tag post.customer.get_profile_image(100,100), class: "rounded-circle" %><br />
                <%= post.customer.full_name %>
                <% end %>
              </td>
              <td><%= link_to post.title, admin_post_path(post.id) %></td>
          <% end %>
            </tr>
          </tbody>
        </table>
          <div><%= paginate @posts %></div>
      </div>
    </div>
  </div>

app/views/admin/posts/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 offset-md-2 border border-secondary mt-5 shadow-lg p-3" style="background-color:#D0C1C2;">
　　<h3 class="mb-2 text-center"><%= @post.customer.full_name %>さんの投稿詳細</h3>
　　<div><%= @post.title %></div>
    <% if @post.images.attached? %>
      <% @post.images.each do |image| %>
        <%= image_tag image.variant(resize_to_limit: [300, 300]) %>
      <% end %>
    <% end %>
    <div class="mt-4 mb-4"><%= @post.body %></div>
    <%= link_to "投稿削除", admin_post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-info rounded-pill" %>

　　<!--コメント機能一覧-->
    <div class="comment_index">
      <%= render "admin/posts/index", post: @post %>
    </div>

    </div>
　</div>
</div>