config/routes.rb
Rails.application.routes.draw do
  #ゲストログイン
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

scope module: :public do
  root to: "homes#top"
  get "about" => "homes#about", as: 'about'
  get "search" => "searches#search"
  resources :notifications, only: [:index]
  delete "destroy_all" => "notifications#destroy_all"
  resources :customers, only: [:index, :show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'

    member do
      get :favorites
    end
  end

  resources :posts, only: [:index, :show, :edit, :new, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]

    resources :comments, only: [:create, :destroy]
  end
end



  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  resources :customers, only: [:index, :show, :destroy]
  resources :posts, only: [:index, :show, :destroy]

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "件") %> のエラーが発生しました。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-info text-center">
    <%= value %><button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer mt-5" style="background-color:#D0C1C2; height:60px; bottom:0px; left:0px; right:0px;">
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#D0C1C2;">
    <a class="navbar-brand" href="/about" style="font-family: cursive;">
      <%= image_tag 'logo.png', :size => '230x50' %>
    </a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
        <div class="navbar-collapse collpse show" id="navbarNavDropdown" style>
          <ul class="navbar-nav ml-auto">


    <% if customer_signed_in? %>
      <li class="nav-item">
        <% if unchecked_notifications.any? %>
        <i class="fa fa-circle" style="color: gold;"></i>
        <% end %>
      <li>
        <%= link_to "通知", notifications_path, class: 'btn btn-outline-light rounded-pill mx-3 my-1' %>
      </li>
      </li>
      <li class="nav-item"><%= link_to "投稿", new_post_path, class: 'btn btn-outline-light rounded-pill mx-3 my-1' %></li>
      <li class="nav-item"><%= link_to "マイページ", customer_path(current_customer), class: 'btn btn-outline-light rounded-pill mx-3 my-1' %></li>
      <li class="nav-item"><%= link_to "会員一覧", customers_path, class: 'btn btn-outline-light rounded-pill mx-3 my-1' %></li>
      <li class="nav-item"><%= link_to "投稿一覧", posts_path, class: 'btn btn-outline-light rounded-pill mx-3 my-1' %></li>
      <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-light rounded-pill mx-3 my-1' %></li>
      <li><%= render 'public/searches/form' %></li>

    <% elsif admin_signed_in? %>
      <li class="nav-item"><%= link_to "投稿一覧", admin_posts_path, class: 'btn btn-outline-light rounded-pill mx-3 my-1' %></li>
      <li class="nav-item"><%= link_to "会員一覧", admin_customers_path, class: 'btn btn-outline-light rounded-pill mx-3 my-1' %></li>
      <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-outline-light rounded-pill mx-3 my-1' %></li>

    <% else %>
      <li class="nav-item"><%= link_to "Top", root_path, class: 'btn btn-outline-light rounded-pill mx-3 my-1' %></li>
      <li class="nav-item"><%= link_to "About", about_path, class: 'btn btn-outline-light rounded-pill mx-3 my-1' %></li>
      <li class="nav-item"><%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-light rounded-pill mx-3 my-1' %></li>
      <li class="nav-item"><%= link_to "ログイン", new_customer_session_path , class: 'btn btn-outline-light rounded-pill mx-3 my-1' %></li>
    <% end %>

        </ul>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fishing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash'  %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>